# Generated by Django 3.2.9 on 2021-11-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('publishing_date', models.DateTimeField(verbose_name='Yayımlanma Tarihi')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
