# Generated by Django 3.2.9 on 2021-11-22 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0003_auto_20211122_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='link',
        ),
        migrations.RemoveField(
            model_name='userentry',
            name='uuid',
        ),
        migrations.AddField(
            model_name='userentry',
            name='rating',
            field=models.CharField(choices=[('b', 'Bad'), ('a', 'Average'), ('e', 'Excellent')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
