# Generated by Django 3.2.9 on 2021-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectme', '0005_auto_20211123_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='video_sec',
            field=models.IntegerField(default=0, verbose_name='Video Süresi Saniye: '),
        ),
        migrations.AddField(
            model_name='userentry',
            name='video_time',
            field=models.IntegerField(default=0, verbose_name='Video Süresi Dakika: '),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='cevap_a',
            field=models.CharField(default='Lorem İpsum A', max_length=150, verbose_name='Şık A'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='cevap_b',
            field=models.CharField(default='Lorem İpsum B', max_length=150, verbose_name='Şık B'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='cevap_c',
            field=models.CharField(default='Lorem İpsum C', max_length=150, verbose_name='Şık C'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='cevap_d',
            field=models.CharField(default='Lorem İpsum D', max_length=150, verbose_name='Şık D'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='cevap_e',
            field=models.CharField(default='Lorem İpsum E', max_length=150, verbose_name='Şık E'),
        ),
    ]
